#datasource.driverClassName=com.mysql.cj.jdbc.Driver
#datasource.url=jdbc:mysql://localhost:3306/scrummaster
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#datasource.username=root
#datasource.password=Ptpl!234

datasource.driverClassName=com.h2.Driver
datasource.url=jdbc:h2:tcp://192.168.2.219/~/scrummaster
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

datasource.username=user1
datasource.password=posidex

enableAutocommit=true
disableLoginMillis = 30000
cors.origin=localhost