datasource.driverClassName=com.mysql.cj.jdbc.Driver
datasource.url=jdbc:mysql://localhost:3306/scrummaster
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
datasource.username=akhil527
datasource.password=Ptpl!234
enableAutocommit=true
disableLoginMillis = 30000
cors.origin=localhost